#!/usr/bin/python
import time

if __name__ == '__main__':
    cadena = None
    print ("Hola")
    print ("Bienvenido a mi juego")
    print ("Empezemos por crear tu heroe")
    print ("Introduce el nombre de tu heroe")
    name = raw_input()
    print ("Introduce el color de cabello de tu heroe")
    hair = raw_input()
    print ("Introduce la edad de tu heroe")
    age = raw_input()
    print ("Vamos a mostrar tu heroe")
    print ("Edad: ", hair)
    print ("Nombre: ", age)
    print ("Cabello: ", name)
    print ("Es correcto? (s/n)")
    raw_input()
    print ("Empezemos")
    time.sleep(1)
    print ("3")
    time.sleep(1)
    print (2)
    time.sleep(1)
    print (1)
    time.sleep(1)
    print ("START")
    time.sleep(1)
    print ("Tu heroe muere, el mundo sucumbe en el caos y PHP lo domina")
    time.sleep(3)
    print ("Adios")